<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HK" failures="1" tests="3" name="Add data and delete data functionality" time="1.634" errors="0" timestamp="2024-03-19T00:38:32 PDT">
  <testcase classname="org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality" name="validateDeleteData" time="0.527"/>
  <testcase classname="org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality" name="validateDeletedDataInGetData" time="0.601"/>
  <testcase classname="org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality" name="addrepo" time="0.399">
    <failure type="java.lang.AssertionError" message="Repo is created in github expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: Repo is created in github expected [201] but found [422]
at org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality.addrepo(ValidateAddAndDeleteData_Functionality.java:105)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addrepo -->
</testsuite> <!-- Add data and delete data functionality -->
